### ISSUE TITLE
Does PyBOBYQA support categorical variables?

### ISSUE THREAD

**Issue by ogencoglu** [numericalalgorithmsgroup/pybobyqa#29]
Can we minimize functions that has both continuous and categorical variables?

**Comment by lindonroberts** [comment]
Unfortuantely not, Py-BOBYQA doesn't have this functionality (and it is fairly tricky to implement).

You can try it by giving Py-BOBYQA an objective function which involves rounding, but I don't expect this will work very well. Something like:

```
def objfun(x):
    category = int(x[0])  # extract real-valued variable and round to integer to get category
    # don't forget to add suitable bounds on the categorical variable
    continuous = x[1:]
    return np.sum(continuous) if category == 0 else np.prod(continuous)
```

If you need a derivative-free solver that handles categorical variables, you could try [NOMAD](https://www.gerad.ca/en/software/nomad/). Otherwise, [pySOT](https://pysot.readthedocs.io/en/latest/) is a global derivative-free optimization solver that allows integer variables.

**Comment by ogencoglu** [comment]
Thanks for the reply and pointers!
